/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
type __SSTIsAny<T> = 0 extends (1 & T) ? true : false;
type __SSTServiceEntrypoint<T> = T extends abstract new (...args: any[]) => infer Instance ? Instance : T;
type __SSTService<T> = __SSTIsAny<T> extends true ? cloudflare.Service : __SSTServiceEntrypoint<T> extends Rpc.WorkerEntrypointBranded ? cloudflare.Service<__SSTServiceEntrypoint<T>> : cloudflare.Service;
declare module "sst" {
  export interface Resource {
    "Backend": __SSTService<typeof import("./backend").default>
    "Frontend": __SSTService<typeof import("./frontend").default>
  }
}

import "sst"
export {}